# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FlagScale Training Dockerfile for MThreads MUSA Platform

# The vendor's PyTorch 2.9.1 image requires a newer host driver for MCCL than
# the current S5000 CI fleet provides. Keep the verified PyTorch 2.7.1 base
# immutable until the fleet driver and vendor image are upgraded together.
ARG BASE_IMAGE=harbor.baai.ac.cn/flagos-dev/transformerengine-fl:manual-20260802-musa-torch2.7.1-e73781e-vllm29ceebd
ARG PKG_MGR=pip
ARG FLAGSCALE_HOME=/opt/flagscale
ARG PIP_DEFAULT_TIMEOUT=300
ARG FLAGSCALE_MEGATRON_REPO=https://github.com/flagos-ai/Megatron-LM-FL.git
ARG FLAGSCALE_MEGATRON_REF=main
ARG FLAGSCALE_TE_VERSION=2.0.0+e73781e

FROM ${BASE_IMAGE} AS base

ARG FLAGSCALE_HOME
ARG FLAGSCALE_MEGATRON_REF

ARG PIP_INDEX_URL=https://pypi.org/simple
ARG PIP_DEFAULT_TIMEOUT
ARG PIP_EXTRA_INDEX_URL
ARG UV_INDEX_URL=${PIP_INDEX_URL}
ARG UV_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy=${HTTP_PROXY}
ARG https_proxy=${HTTPS_PROXY}
ARG no_proxy=${NO_PROXY}

ENV FLAGSCALE_HOME=${FLAGSCALE_HOME}
ENV PIP_DEFAULT_TIMEOUT=${PIP_DEFAULT_TIMEOUT}
ENV FLAGSCALE_DEPS=${FLAGSCALE_HOME}/deps
ENV FLAGSCALE_DOWNLOADS=${FLAGSCALE_HOME}/downloads
ENV MUSA_HOME=/usr/local/musa
ENV MPI_HOME=/usr/local/openmpi
ENV PATH="${MUSA_HOME}/bin:${MPI_HOME}/bin:/root/.local/bin:$PATH"
ENV LD_LIBRARY_PATH="${MUSA_HOME}/lib:${MPI_HOME}/lib:/usr/local/lib:$LD_LIBRARY_PATH"

LABEL io.flagscale.megatron-lm-fl.revision=${FLAGSCALE_MEGATRON_REF}

COPY tools/install/musa/env.sh /etc/profile.d/flagscale-env.sh

WORKDIR /workspace

FROM base AS deps

ARG PKG_MGR
ARG FLAGSCALE_HOME
ARG FLAGSCALE_MEGATRON_REPO
ARG FLAGSCALE_MEGATRON_REF
ARG FLAGSCALE_TE_VERSION

ARG PIP_INDEX_URL
ARG PIP_DEFAULT_TIMEOUT
ARG PIP_EXTRA_INDEX_URL
ARG UV_INDEX_URL
ARG UV_EXTRA_INDEX_URL
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy=${HTTP_PROXY}
ARG https_proxy=${HTTPS_PROXY}
ARG no_proxy=${NO_PROXY}

ENV PIP_INDEX_URL=${PIP_INDEX_URL}
ENV PIP_DEFAULT_TIMEOUT=${PIP_DEFAULT_TIMEOUT}
ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ENV UV_INDEX_URL=${UV_INDEX_URL}
ENV UV_EXTRA_INDEX_URL=${UV_EXTRA_INDEX_URL}
ENV FLAGSCALE_MEGATRON_REPO=${FLAGSCALE_MEGATRON_REPO}
ENV FLAGSCALE_MEGATRON_REF=${FLAGSCALE_MEGATRON_REF}
ENV FLAGSCALE_TE_VERSION=${FLAGSCALE_TE_VERSION}

COPY tools/install /workspace/tools/install
COPY requirements /workspace/requirements

RUN --mount=type=cache,target=/root/.cache/pip \
    . /etc/profile.d/flagscale-env.sh && \
    chmod +x /workspace/tools/install/*.sh && \
    chmod +x /workspace/tools/install/utils/*.sh && \
    chmod +x /workspace/tools/install/musa/*.sh && \
    cd /workspace && \
    FLAGSCALE_HOME=${FLAGSCALE_HOME} FLAGSCALE_MUSA_BUILD_NO_DEVICE=true \
    ./tools/install/install.sh --platform musa --task train --pkg-mgr ${PKG_MGR} --no-system && \
    python -m pip show torch-musa >/dev/null && \
    python -m pip show transformer-engine >/dev/null && \
    rm -rf /workspace

FROM deps AS dev

CMD ["/bin/bash"]

FROM base AS release

ARG PKG_MGR
ARG FLAGSCALE_HOME
ARG FLAGSCALE_MEGATRON_REPO
ARG FLAGSCALE_MEGATRON_REF
ARG FLAGSCALE_TE_VERSION

ARG PIP_INDEX_URL
ARG PIP_DEFAULT_TIMEOUT
ARG PIP_EXTRA_INDEX_URL
ARG UV_INDEX_URL
ARG UV_EXTRA_INDEX_URL
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy=${HTTP_PROXY}
ARG https_proxy=${HTTPS_PROXY}
ARG no_proxy=${NO_PROXY}

ENV PIP_INDEX_URL=${PIP_INDEX_URL}
ENV PIP_DEFAULT_TIMEOUT=${PIP_DEFAULT_TIMEOUT}
ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ENV UV_INDEX_URL=${UV_INDEX_URL}
ENV UV_EXTRA_INDEX_URL=${UV_EXTRA_INDEX_URL}
ENV FLAGSCALE_MEGATRON_REPO=${FLAGSCALE_MEGATRON_REPO}
ENV FLAGSCALE_MEGATRON_REF=${FLAGSCALE_MEGATRON_REF}
ENV FLAGSCALE_TE_VERSION=${FLAGSCALE_TE_VERSION}

COPY tools/install /workspace/tools/install
COPY requirements /workspace/requirements

RUN --mount=type=cache,target=/root/.cache/pip \
    . /etc/profile.d/flagscale-env.sh && \
    chmod +x /workspace/tools/install/*.sh && \
    chmod +x /workspace/tools/install/utils/*.sh && \
    chmod +x /workspace/tools/install/musa/*.sh && \
    cd /workspace && \
    FLAGSCALE_HOME=${FLAGSCALE_HOME} FLAGSCALE_MUSA_BUILD_NO_DEVICE=true \
    ./tools/install/install.sh --platform musa --task train --pkg-mgr ${PKG_MGR} --no-system --no-dev && \
    python -m pip show torch-musa >/dev/null && \
    python -m pip show transformer-engine >/dev/null && \
    rm -rf /workspace

CMD ["/bin/bash"]
